# Generated by Django 5.2.10 on 2026-01-13 01:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import iasd.users.managers
import iasd.users.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telefone', models.CharField(blank=True, help_text='Formato esperado: (00) 0 0000-0000', max_length=16, null=True, validators=[django.core.validators.RegexValidator(message='Telefone deve estar no formato (00) 0 0000-0000', regex='^\\(\\d{2}\\)\\s\\d\\s\\d{4}-\\d{4}$')], verbose_name='Telefone')),
                ('cep', models.CharField(blank=True, max_length=9, null=True, validators=[django.core.validators.RegexValidator(message='CEP deve estar no formato XXXXX-XXX', regex='^\\d{5}-?\\d{3}$')], verbose_name='CEP')),
                ('rua', models.CharField(blank=True, max_length=200, verbose_name='Logradouro')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('bairro', models.CharField(blank=True, max_length=100, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('complemento', models.CharField(blank=True, max_length=200, null=True, verbose_name='Complemento')),
                ('redes_sociais', models.CharField(blank=True, max_length=200, verbose_name='Redes sociais')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of User')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrador'), ('MEMBRO', 'Membro'), ('VISITANTE', 'Visitante'), ('EMPREGADO', 'Empregado')], default='MEMBRO', max_length=20, verbose_name='Tipo de Usuário')),
                ('username', models.CharField(blank=True, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, null=True, unique=True, verbose_name='username')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('membro_responsavel', models.ForeignKey(blank=True, limit_choices_to={'role': 'MEMBRO'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitantes_trazidos', to=settings.AUTH_USER_MODEL, verbose_name='Membro Responsável / Contato')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', iasd.users.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Membro',
            fields=[
            ],
            options={
                'verbose_name': 'Membro',
                'verbose_name_plural': 'Membros',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', iasd.users.models.MembroManager()),
            ],
        ),
        migrations.CreateModel(
            name='Visitante',
            fields=[
            ],
            options={
                'verbose_name': 'Visitante',
                'verbose_name_plural': 'Visitantes',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('users.user',),
            managers=[
                ('objects', iasd.users.models.VisitanteManager()),
            ],
        ),
    ]
