# Generated by Django 5.2.10 on 2026-01-15 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('eventos', '0001_initial'),
        ('ministerios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ministerio_responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='ministerios.ministerio'),
        ),
        migrations.AddField(
            model_name='agendamento',
            name='evento',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agendamento', to='eventos.evento'),
        ),
    ]
