# Generated by Django 5.2.10 on 2026-01-15 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamento',
            options={'ordering': ['data', 'horario_inicio']},
        ),
        migrations.RenameField(
            model_name='agendamento',
            old_name='data_final',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='agendamento',
            name='data_inicio',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='evento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to='eventos.evento'),
        ),
    ]
