# Generated by Django 5.2.10 on 2026-01-15 22:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ministerio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('lider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ministerios_liderados', to='users.membro')),
                ('membros', models.ManyToManyField(blank=True, related_name='ministerios', to='users.membro')),
            ],
        ),
    ]
